### ISSUE TITLE
Action: pack

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/RenderChan#14]
```renderchan --action pack some-file.blend``` - to pack file with all dependencies into single archive.

**Comment by scribblemaniac** [comment]
Could we maybe make pack also automatically try to convert absolute paths to relative ones?

**Comment by morevnaproject** [comment]
For this to work we will need to implement path replacing function for each module. A kind of RenderChanModule.replace("old_path","new_path"). By default it will return False. Then each module can override this function with its own implementation. I believe we can implement this for all animation formats that we support currently (most of them are XML files and for Blender case this could be done through Python scripting).

This might require some work, but I wanted to have such function anyway, because we can use it for aset management. Imagine, if we will add "file move" function to RenderChan. In this case RenderChan  moves the file to new location and updates all links for all related files and the moved file itself. This would be extremely useful. 

In general case we can hit some (closed?) binary format, that wouldn't be possible to implement replace() function. In this case we can just throw warning and list links that are failed to update.

**Comment by scribblemaniac** [comment]
Yes it would have to be handled by each module. As you mentioned the xml formats should be fairly straightforward, and blender is even easier, you should just have to call `bpy.ops.file.make_paths_relative`.

That moving function sounds very interesting as well. I definitely think that would come in handy.

**Comment by morevnaproject** [comment]
> and blender is even easier, you should just have to call bpy.ops.file.make_paths_relative().

My proposal is to introduce replace() function instead of make_relative(). ^__^  Renderchan will take a list of dependencies of a file (as it's always gets through analyze() function), then for each absolute path entry it calls replace("absolute_path", "relative_path) for a given file. That will allow to utilize the same function for move().

**Comment by scribblemaniac** [comment]
Ah, I see why you brought that up now ^_^, yeah that sounds good too.
