### ISSUE TITLE
Improve blender stereo camera handling

### ISSUE THREAD

**Issue by scribblemaniac** [morevnaproject/RenderChan#21]
Blender has [naming conventions](https://www.blender.org/manual/rigging/armatures/editing/properties.html#naming-conventions) for right and left objects that is used for armatures. We already have support for the "name.left" and "name.right" formats by the looks of the code, but I would propose we take it a step further and implement the naming conventions linked above. This will help provide continuity with Blender and may be more familiar to Blender artists. It should be fairly straightforward to implement a regex script that matches these patterns.

**Comment by scribblemaniac** [comment]
Ah silly me, I totally forgot Blender added native support for stereo rendering a while back. I guess there isn't much of a point to this then. We can't just remove this feature if you want to maintain backwards compatibility, but there isn't much of a point doing any more work here. I'm closing the issue for now, it can be reopened if you still want this done.

**Comment by morevnaproject** [comment]
I think we have to update our current support for stereo rendering to match the Blender's native features. The only change required is to change mechanism of the active camera selection. And yes, it would be nice to keep the old mechanism as well, to keep backward compatibility. Not sure how the choice between the old and new system will be done (probably, RenderChan will be able to guess the mode by inspecting the camera options). Thanks for bringing this up!

**Comment by morevnaproject** [comment]
Merged.
