### ISSUE TITLE
Update krita module

### ISSUE THREAD

**Issue by scribblemaniac** [morevnaproject/RenderChan#32]
They just released v3.0 which supposedly has some support for animations. I'm guessing the module will have to be updated some to support that.

**Comment by morevnaproject** [comment]
We need a way to export Krita animation from commandline. The relevant ticket submitted here - https://bugs.kde.org/show_bug.cgi?id=364046

**Comment by morevnaproject** [comment]
Support for animation export just landed to Krita! - 
https://phabricator.kde.org/R37:b3ec22593c96

Now we can go with that issue. ^__^

**Comment by morevnaproject** [comment]
Waiting for nightly Krita appimage now... - https://binary-factory.kde.org/job/Krita_Nightly_Appimage_Build/

**Comment by morevnaproject** [comment]
Appimage is available here now - https://binary-factory.kde.org/job/Krita_Nightly_Appimage_Build/407/artifact/krita-4.2.0-pre-alpha-bb0edcc-x86_64.appimage
