### ISSUE TITLE
Change license to "Modified BSD"

### ISSUE THREAD

**Issue by morevnaproject** [morevnaproject/RenderChan#38]
I would like to change license of RenderChan from "GPLv3" to more permissive one - "Modified BSD" (aka "new BSD"). From my point of view this would open more possibilities to integrate RenderChan with other tools. See https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses.

In order to do so, I need agreement from al contributors. @scribblemaniac and @blackwarthog, please write if you agree or not in the comments.

**Comment by scribblemaniac** [comment]
Yes, I'm fine with that. You can change the Blender plugin as well if you want ^_^

**Comment by blackwarthog** [comment]
I agree, however i think GNU was better.
