### ISSUE TITLE
Enhacement: Support Natron

### ISSUE THREAD

**Issue by triceratops1** [morevnaproject/RenderChan#39]
Natron: An OSS VFX software, just like Nuke

natron.fr

**Comment by scribblemaniac** [comment]
This has already been requested in #18. It will get done...eventually.

**Comment by scribblemaniac** [comment]
In fact, I already have most of it done here:
https://github.com/scribblemaniac/RenderChan/tree/natron

I can't remember what part wasn't working (probably handling multiple output nodes), but it may suffice for your purposes.

**Comment by morevnaproject** [comment]
@scribblemaniac Maybe it worts to merge it already. what do you think?

**Comment by scribblemaniac** [comment]
Probably not. I'm sure I had a good reason for not merging it before. Unpredictable behavior may be worse than no behavior.

I'll try and figure out the current state of that branch when I get a chance, but it could be a while. There are a lot of things I still want to do for this project, I've just been way too busy.

**Comment by morevnaproject** [comment]
@scribblemaniac I can perfectly understand that. No problem, let's keep that unmerged for now. ^__^
