### ISSUE TITLE
empty projet failing to render

### ISSUE THREAD

**Issue by zeograd** [morevnaproject/RenderChan#45]
It's probably an issue which could be fixed by exchanging on a forum, but as renderchan doesn't have a large community yet and it might help to have a public answer (instead of bothering privately the dev team), I prefer to ask here as an issue.

I try to create a renderchan project "from scratch". I picked the project.conf from the sources and create a .blend file from scratch including a "intro.svg.png" dependency as included image in the VSE.
At no point, whether calling it with --deps or without, the "intro.svg.png" dependency tried to trigger a file generation (I've dived into debugging step by step and at no point the filename is even considered to find out which module would be usable to generate the missing file)

For the sake of understanding how to start a new project in renderchan without relying blindly on the provided template, I'd like to know what is missing to trigger deps generation.

Thanks in advance

(Attached is the empty project attempt.)

[renderchan_simple_proj.tar.gz](https://github.com/morevnaproject/RenderChan/files/2303105/renderchan_simple_proj.tar.gz)

**Comment by zeograd** [comment]
Looking at it more in details, it may be related to the way resources are added in the .blend file
It should be the rendered file in ./render which is used and not a file in the same directory as the source file. Does that sound right ?

**Comment by scribblemaniac** [comment]
@zeograd Yes, it sounds like you might have the rendered files in the wrong place. Ideally, you should just be able to call `renderchan intro.svg` and it will render that file to the correct place and you can use it in any other projects from there. Unfortunately it seems like there's a bug with our Inkscape rendering module at the moment, so your svg file will only render properly if in Inkscape you go to Document Properties and set the custom size to a whole number with px units.

**Comment by zeograd** [comment]
Indeed, the issue was with the location of the included file.
So, for future reference, a fresh new project workflow could be
- copy the default project.conf in your project directory
- create placeholder dependecy files (.svg, .sifz, ...)
- render them (calling renderchan without option on them directly)
- create a project wide .blend file referencing rendered placeholders (in ./render)

From then on, one can edit the placeholders and the .blend main file and call renderchan to have the project rendered with the latest version of all of those.

Thanks for confirming my misundertanding !

**Comment by morevnaproject** [comment]
> It's probably an issue which could be fixed by exchanging on a forum, but as renderchan doesn't have a large community yet ...

I agree, it would be nice to set up a community support forum at some point! After we will release version 1.0, perhaps.

> So, for future reference, a fresh new project workflow could be ...

Yes, this is exactly how we do! It is a shame I still cannot find a time to write a full-featured tutorial. ^__^ " Thanks for writing a hint here! ^__^
