### ISSUE TITLE
Additional flags

### ISSUE THREAD

**Issue by scribblemaniac** [morevnaproject/RenderChan#5]
I've been working on the Blender plugin quite a bit the past few days and it is nearing a usable state. Some additional command line flags need to be added to RenderChan before it can be fully functional however. These are the features that are needed or would be useful for the plugin:
- Check if any of the dependencies have been modified. Just like --deps, except don't actually do anything, maybe just print the results (this could be part of the previously discussed --dry-run flag)
- Given a source file, give the path that it will be rendered to, or multiple paths if the output is a sequence.
- Reverse lookup. Given the path of the rendered output, output the path of the source file. This should print out a unique, easily identifiable output if the input file was not rendered as part of a RenderChan project.
- List the names of all profiles specified in project configuration files (--list-profiles). This low priority as it is not strictly necessary, we can simply have a text box for the user to type the name of the profile they want until we implement this.
- Get available file formats. This is another low priority item, because I probably won't implement file filtering any time soon. It would return a list all of the import extensions, but only for modules that can be loaded (have the correct binaries and stuff).
- Just generally make it easier for programs to parse. A status prefix at the beginning of the line, such as "Warning:", "Error:", "Info:", etc. is nice because you can use startsWith to filter the output. You've already got that in some places, but enforcing it in all messages would be nice. Going a step further, you could have a --json flag to output all of the data in a json format specifically for parsing by other programs.
- Render even if the source has not changed. Okay admittedly this is not that useful for the plugin, but I thought it would be good to have a -f or --force flag. While the source may not have changed, perhaps the renderer has. For example, maybe a new version of Synfig comes out that has better anti aliasing and you want to rerender just the .sif files without going in and modifying them all. You could go into the render folder, figure out which files to delete, and do it that way, but I think this would just be more convenient.

I will try and get some of these working when I can figure out how everything in the cli file works. Most of these features should be quite straightforward to implement, but I would still love some help with this ^_^
I'd love to hear your thoughts and suggestions for all of this.

**Comment by morevnaproject** [comment]
Hello @scribblemaniac! Thank you for keeping me updated!
I have a suggestion. Instead of trying to communicate with RenderChan via commandline it might be better to import RenderChan module directly into Blender. In this case it is possible to use RenderChan API directly.

You can do that like this:

    # find directory of renderchan module
    renderchanPath=find_executable("renderchan")
    modulePath = os.path.join(os.path.dirname(os.path.dirname(renderchanPath)))
    if os.path.exists(os.path.join(modulePath, 'renderchan', '__init__.py')):
       sys.path.insert(0, modulePath)
    # import modules
    from renderchan.file import RenderChanFile
    from renderchan.core import RenderChan

    # do something
    renderchan = RenderChan()

    taskfile = RenderChanFile("/path/to/your/project/0001/file.sif", renderchan.modules, renderchan.projects)
    filepath = taskfile.getPath()
    # result: /path/to/your/project/0001/file.sif
    renderpath = taskfile.getRenderPath()
    # result: /path/to/your/project/render/0001/file.sif

    # it is also possible to create RenderChanFile by giving filename form "render" directory
    taskfile = RenderChanFile("/path/to/your/project/render/0001/file.sif", renderchan.modules, renderchan.projects)
    filepath = taskfile.getPath()
    # result: /path/to/your/project/0001/file.sif
    renderpath = taskfile.getRenderPath()
    # result: /path/to/your/project/render/0001/file.sif

You can look at cli.py file, which does mostly the same. ^__^

This doesn't solve number (1) and (7) - the code still have to be modified to make this possible. 

Also, I agree, that having "--force" option  for CLI would be useful (as well as "--dry-run").

**Comment by morevnaproject** [comment]
Ah, wait, I forgot one thing. Blender uses Python3 and RenderChan is currently on Python2. :(

Actually, it would be really nice to add Python3 compatibility - https://docs.python.org/3/howto/pyporting.html

Historical note: At the beginning of the project  I was forced to go with Python2, because initially I was planning to use RenderChan with Puli renderfarm, which is in Python2. But Puli turned to be unusable case for my situation (because of lack of GUI module) and I have switched to Afanasy (which is safe for both Python2 and Python3.

**Comment by scribblemaniac** [comment]
That would be a much more elegant solution. I had earlier considered copying code into the plugin from renderchan, which was impractical. I really should've thought of this though. I'll see what I can do.

**Comment by scribblemaniac** [comment]
@morevnaproject Ping. You may have missed the questions in my last post because they were edited in shortly after posting.

**Comment by morevnaproject** [comment]
Yes, I have missed it, sorry. I would like to keep compatibility with python2, much like the same way as CGRU/Afanasy does. I don't plan to rip out Puli for now - maybe someone will find it interesting when we make a stable release of RenderChan 1.0. ^__^

**Comment by scribblemaniac** [comment]
In that's case it seems like I have a bit more work to do on #9.

**Comment by morevnaproject** [comment]
Don't worry. Since it's already a lot of work done, I prefer to merge it. We can add python2 support later by using __future__ module (if we will really need that).

**Comment by morevnaproject** [comment]
This way you can keep working on the Blender integration module (which is more high-priority task). ^__^

**Comment by scribblemaniac** [comment]
Will do then ^_^

**Comment by morevnaproject** [comment]
Huh. "Mikros Image has stopped any further development regarding this software" - http://opensource.mikrosimage.eu/puli.html
I can wash my hands.
